# Generated by Django 4.2.4 on 2024-12-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_taskstatus_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='named',
            new_name='name',
        ),
    ]
